bug:
  - '*bug*'
  - '*error*'
  - '*fail*'
  - '*crash*'
  - '*broken*'
  - '*not work*'
  - '*doesn''t work*'
  - '*traceback*'
  - '*exception*'

enhancement:
  - '*feature*'
  - '*enhance*'
  - '*improve*'
  - '*add*'
  - '*support*'
  - '*request*'
  - '*would like*'
  - '*could*'
  - '*should*'

documentation:
  - '*doc*'
  - '*readme*'
  - '*guide*'
  - '*tutorial*'
  - '*example*'
  - '*help*'
  - '*clarif*'

question:
  - '*question*'
  - '*how*'
  - '*why*'
  - '*what*'
  - '*where*'
  - '*when*'
  - '?*'

configuration:
  - '*config*'
  - '*setup*'
  - '*install*'
  - '*yaml*'
  - '*option*'
  - '*setting*'

integration:
  - '*sensor*'
  - '*binary_sensor*'
  - '*device*'
  - '*entity*'
  - '*platform*'
  - '*coordinator*'

api:
  - '*api*'
  - '*meraki*'
  - '*dashboard*'
  - '*network*'
  - '*organization*'
  - '*rate limit*'
  - '*authentication*'
  - '*token*'

MT:
  - '*MT*'
  - '*environmental*'
  - '*temperature*'
  - '*humidity*'
  - '*tvoc*'
  - '*pm25*'
  - '*water*'
  - '*button*'

performance:
  - '*slow*'
  - '*timeout*'
  - '*performance*'
  - '*optimization*'
  - '*memory*'
  - '*cpu*' 