name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

sort-direction: descending

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
    # Parse conventional commits for features
    collapse-after: 5
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
    collapse-after: 5
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
      - 'ci'
      - 'build'
      - 'refactor'
    collapse-after: 5
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
    collapse-after: 3
  - title: '🔒 Security'
    labels:
      - 'security'
    collapse-after: 3

# Template for individual changes - works with both PRs and commits
change-template: '- $TITLE @$AUTHOR${{#if number}} (#${{number}})${{else}} (${{commit}})${{/if}}'
change-title-escapes: '\<*_&'

# Use conventional commits for automatic categorization
autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'fix'
    title:
      - '/^fix(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'chore'
    title:
      - '/^chore(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'docs'
    title:
      - '/^docs(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'ci'
    title:
      - '/^ci(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'build'
    title:
      - '/^build(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'refactor'
    title:
      - '/^refactor(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'perf'
    title:
      - '/^perf(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'test'
    title:
      - '/^test(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'style'
    title:
      - '/^style(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'security'
    title:
      - '/^security(\(.+\))?(!)?\s*:\s*(.+)$/i'
  - label: 'breaking'
    title:
      - '/^.+!:\s*(.+)$/i'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
      - 'feat'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
      - 'docs'
      - 'ci'
      - 'build'
      - 'refactor'
      - 'perf'
      - 'test'
      - 'style'
      - 'security'
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Installation

  ### HACS (Recommended)
  1. Add this repository as a custom repository in HACS
  2. Install "Meraki Dashboard" integration
  3. Restart Home Assistant

  ### Manual Installation
  1. Download the `meraki_dashboard.zip` file from the Assets section below
  2. Extract to `custom_components/meraki_dashboard/` in your Home Assistant config directory
  3. Restart Home Assistant

  ## Contributors

  Thanks to all contributors who made this release possible! 🎉

exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'question'
  - 'invalid'
  - 'wontfix'
  - 'dependencies' # Exclude dependabot updates from release notes

# Include commits and handle cases where there are no PRs
include-pre-releases: false
prerelease: false

# Enable commit-based release notes (not just PRs)
commitish: main
filter-by-commitish: true

# Replacers to clean up commit messages for better changelog entries
replacers:
  - search: '/^(feat|fix|docs|style|refactor|perf|test|chore|ci|build)(\(.+\))?(!)?\s*:\s*(.+)$/gm'
    replace: '$4'
