name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🔒 Security'
    labels:
      - 'security'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
      - 'dependencies'
  default: patch

template: |
  ## Changes

  $CHANGES

  ## Installation

  ### HACS (Recommended)
  1. Add this repository as a custom repository in HACS
  2. Install "Meraki Dashboard" integration
  3. Restart Home Assistant

  ### Manual Installation
  1. Download the `meraki_dashboard.zip` file from the Assets section below
  2. Extract to `custom_components/meraki_dashboard/` in your Home Assistant config directory
  3. Restart Home Assistant

  ## Contributors

  Thanks to all contributors who made this release possible! 🎉

exclude-labels:
  - 'skip-changelog'
  - 'duplicate'
  - 'question'
  - 'invalid'
  - 'wontfix' 