# Jekyll configuration for GitHub Pages
title: "Meraki Dashboard Home Assistant Integration"
description: "Monitor your Cisco Meraki devices through Home Assistant"
baseurl: "/meraki-dashboard-ha"
url: "https://rknightion.github.io"

# Repository info
repository: rknightion/meraki-dashboard-ha

# GitHub Pages theme and plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings with Mermaid support
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  devices:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "devices"
    values:
      layout: "device"

# Navigation structure
navigation:
  - title: "Home"
    url: "/"
  - title: "Development"
    url: "/development"
  - title: "FAQ"
    url: "/faq"
  - title: "Changelog"
    url: "/changelog"

# SEO
author: "rknightion"
twitter:
  username: rknightion
social:
  name: Meraki Dashboard HA
  links:
    - https://github.com/rknightion/meraki-dashboard-ha

# Google Analytics (optional)
# google_analytics: G-XXXXXXXXXX
