name: Dependabot Pull Request
on: pull_request
jobs:
  dependabot:
    permissions:
      pull-requests: write
      issues: write
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'owner/my_repo'
    steps:
    - name: Fetch Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v2
      with:
        alert-lookup: true
        compat-lookup: true
        github-token: "${{ secrets.PAT_TOKEN }}"

    - name: Dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        
    - name: Add a label for all production dependencies
      if: steps.metadata.outputs.dependency-type == 'direct:production'
      run: gh pr edit "$PR_URL" --add-label "production"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}