name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: read
  statuses: read
  actions: write
  discussions: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json

      # Enable auto-merge for release PRs immediately after creation
      - name: Enable auto-merge for release PR
        if: ${{ steps.release.outputs.pr }}
        run: |
          PR_NUMBER=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.number')
          echo "Enabling auto-merge for PR #${PR_NUMBER}"
          gh pr merge --auto --squash "$PR_NUMBER" || echo "Auto-merge failed, but continuing..."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
