name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: meraki-dashboard-ha
          include-v-in-tag: true
          changelog-types: |
            [
              {"type":"feat","section":"🚀 Features","hidden":false},
              {"type":"fix","section":"🐛 Bug Fixes","hidden":false},
              {"type":"perf","section":"⚡ Performance Improvements","hidden":false},
              {"type":"revert","section":"⏪ Reverts","hidden":false},
              {"type":"docs","section":"📚 Documentation","hidden":false},
              {"type":"style","section":"💄 Styles","hidden":true},
              {"type":"chore","section":"🧰 Maintenance","hidden":false},
              {"type":"refactor","section":"♻️ Code Refactoring","hidden":false},
              {"type":"test","section":"✅ Tests","hidden":true},
              {"type":"build","section":"🔧 Build System","hidden":true},
              {"type":"ci","section":"👷 CI/CD","hidden":true}
            ]

  # Build and attach the integration zip when a release is created
  build-and-upload:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create integration zip
        run: |
          cd custom_components/meraki_dashboard
          zip -r ../../meraki_dashboard.zip . -x "*.pyc" "*/__pycache__/*" "*.git*"
      
      - name: Upload integration zip to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} meraki_dashboard.zip --clobber 