name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: read
  statuses: read
  actions: write
  discussions: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json

  # Enable auto-merge for release-please PRs
  enable-auto-merge:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.pr }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable auto-merge for release PR
        run: |
          PR_NUMBER=$(echo '${{ needs.release-please.outputs.pr }}' | jq -r '.number')
          gh pr merge --auto --squash "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build and attach the integration zip when a release is created
  build-and-upload:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update docs changelog for release
        run: |
          # Create header for docs changelog
          cat > docs/changelog.md << 'EOF'
          ---
          layout: default
          title: Changelog
          description: Release history and changelog for the Meraki Dashboard Home Assistant Integration
          ---

          # Changelog

          All notable changes to this project are documented here. The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

          <div class="alert alert-info" role="alert">
            <i class="bi bi-info-circle me-2"></i>
            <strong>Note:</strong> This changelog is automatically generated from our git commit history using <a href="https://github.com/googleapis/release-please">release-please</a>. For the complete changelog including technical details, see the full <a href="{{ site.repository }}/blob/main/CHANGELOG.md">CHANGELOG.md</a> in our repository.
          </div>

          EOF

          # Extract content from root CHANGELOG.md (skip first few lines)
          tail -n +8 CHANGELOG.md | sed 's/## \[/### [/g' >> docs/changelog.md

          # Add footer
          cat >> docs/changelog.md << 'EOF'

          ## Support

          - **Questions**: Check our [FAQ](faq) or see the troubleshooting section on the [main page](/)
          - **Issues**: Report bugs on [GitHub Issues]({{ site.repository }}/issues)
          - **Discussions**: Join the conversation on [GitHub Discussions]({{ site.repository }}/discussions)

          ## Links

          - **[Full Changelog]({{ site.repository }}/blob/main/CHANGELOG.md)** - Complete technical changelog
          - **[Releases]({{ site.repository }}/releases)** - Download specific versions
          - **[Release Notes]({{ site.repository }}/releases)** - Detailed release information
          EOF

      - name: Create integration zip
        run: |
          cd custom_components/meraki_dashboard
          zip -r ../../meraki_dashboard.zip . -x "*.pyc" "*/__pycache__/*" "*.git*"

      - name: Upload integration zip to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} meraki_dashboard.zip --clobber
